language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  #- "pypy-5.3.1"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
# command to run tests
script:
  - py.test --cov=training_data.py --cov=gym_2048/envs/game2048_env.py
  - python simple_rl_agent.py
after_success:
  - if [[ $ENV == python=3.4* ]]; then
        coveralls;
    fi
